[package]
name = "contention_cpu"
version = "0.2.0"
authors = ["<shuwenjsun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_affinity = "=0.5.10"
rand = "=0.8.4"
