secondary = false
primary_core = 3
cores = [3]
strict = false
pool_size = 3072
cache_size = 32
duration = 350
[[ports]]
  name = "0000:01:00.1"
  rxq = 0
  txq = 0
  rx_cores = [3]
  tx_cores = [3]
  rxd = 128
  txd = 128
  loopback = false
  tso = false
  csum = false
