secondary = false
primary_core = 0
cores = [0]
strict = false
pool_size = 3072
cache_size = 32
duration = 180
[[ports]]
  name = "0000:01:00.1"
  rxq = 0
  txq = 0
  rx_cores = [0]
  tx_cores = [0]
  rxd = 128
  txd = 128
  loopback = false
  tso = false
  csum = false
