secondary = false
primary_core = 0
cores = [4, 5]
strict = false
pool_size = 3072
cache_size = 32
duration = 180
[[ports]]
  # name = ["0000:01:00.0", "0000:01:00.1"]
  name = "0000:01:00.0"
  rxq = 0
  txq = 0
  rx_cores = [4]
  tx_cores = [4]
  rxd = 128
  txd = 128
  loopback = false
  tso = false
  csum = false
[[ports]]
  # name = ["0000:01:00.0", "0000:01:00.1"]
  name = "0000:01:00.1"
  rxq = 0
  txq = 0
  rx_cores = [5]
  tx_cores = [5]
  rxd = 128
  txd = 128
  loopback = false
  tso = false
  csum = false
